export const EVENTS = [
  {
    id: '1',
    title: 'Annual Science Fair',
    category: 'Academic',
    date: '2025-05-10',
    time: '10:00 AM',
    location: 'Main Hall, Block A',
    description:
      'The annual science fair showcases student projects from all departments. Come present your research, innovations, and experiments. Prizes will be awarded in multiple categories including Best Innovation, Best Research, and Best Presentation.',
    organizer: 'Science Department',
    color: '#7c3aed',
    icon: '🔬',
    tags: ['Science', 'Research', 'Competition'],
  },
  {
    id: '2',
    title: 'Freshers Welcome Party',
    category: 'Social',
    date: '2025-05-15',
    time: '6:00 PM',
    location: 'College Auditorium',
    description:
      'A grand welcome for all new students joining the college this semester. Enjoy live music, food stalls, games, and activities. Meet your seniors, faculty, and fellow freshers in a fun-filled evening.',
    organizer: 'Student Council',
    color: '#db2777',
    icon: '🎉',
    tags: ['Social', 'Freshers', 'Fun'],
  },
  {
    id: '3',
    title: 'Mid-Term Examinations',
    category: 'Exam',
    date: '2025-05-20',
    time: '9:00 AM',
    location: 'Exam Halls 1-5',
    description:
      'Mid-term examinations for all departments. Students must carry their ID cards and admit slips. Mobile phones are strictly prohibited in exam halls. Refer to the official timetable for your subject schedule.',
    organizer: 'Examination Cell',
    color: '#dc2626',
    icon: '📝',
    tags: ['Exam', 'Important', 'Academic'],
  },
  {
    id: '4',
    title: 'Career Fair 2025',
    category: 'Career',
    date: '2025-05-25',
    time: '11:00 AM',
    location: 'Sports Ground',
    description:
      'Over 50 top companies will be present for campus recruitment. Bring multiple copies of your updated resume and dress professionally. Pre-registration is mandatory on the college portal.',
    organizer: 'Placement Cell',
    color: '#059669',
    icon: '💼',
    tags: ['Career', 'Jobs', 'Placement'],
  },
  {
    id: '5',
    title: 'Cultural Night',
    category: 'Cultural',
    date: '2025-06-01',
    time: '7:00 PM',
    location: 'Open Air Theatre',
    description:
      'A spectacular evening of cultural performances including dance, music, drama, and poetry. Students from all departments will showcase their talents. Entry is free for all students.',
    organizer: 'Cultural Committee',
    color: '#d97706',
    icon: '🎭',
    tags: ['Cultural', 'Dance', 'Music'],
  },
  {
    id: '6',
    title: 'Blood Donation Camp',
    category: 'Social',
    date: '2025-06-05',
    time: '9:00 AM',
    location: 'Health Center',
    description:
      'Annual blood donation camp in collaboration with City Hospital. All healthy students and staff are encouraged to donate. Donors will receive certificates and refreshments.',
    organizer: 'NSS Unit',
    color: '#e11d48',
    icon: '🩸',
    tags: ['Social', 'Health', 'Community'],
  },
  {
    id: '7',
    title: 'Sports Day 2025',
    category: 'Sports',
    date: '2025-06-10',
    time: '8:00 AM',
    location: 'Main Sports Ground',
    description:
      'Annual sports day featuring track and field events, team sports, and fun activities. Inter-department competitions in cricket, football, basketball, and volleyball.',
    organizer: 'Sports Committee',
    color: '#2563eb',
    icon: '⚽',
    tags: ['Sports', 'Competition', 'Team'],
  },
  {
    id: '8',
    title: 'Alumni Meet 2025',
    category: 'Academic',
    date: '2025-06-20',
    time: '5:00 PM',
    location: 'Conference Hall',
    description:
      'Annual alumni meet where former students return to share their experiences and industry insights. Networking sessions, panel discussions, and dinner included.',
    organizer: 'Alumni Association',
    color: '#7c3aed',
    icon: '🎓',
    tags: ['Alumni', 'Networking', 'Career'],
  },
];

export const ALERTS = [
  {
    id: 'a1',
    title: 'Fee Submission Deadline',
    message: 'Last date for semester fee submission is May 30. Late fee of Rs. 500 will be charged after the deadline.',
    type: 'warning',
    time: '2 hours ago',
    read: false,
  },
  {
    id: 'a2',
    title: 'Library Books Due',
    message: 'Please return all borrowed library books before May 18 to avoid fines.',
    type: 'info',
    time: '5 hours ago',
    read: false,
  },
  {
    id: 'a3',
    title: 'Class Cancelled – CS101',
    message: 'Data Structures lecture scheduled for tomorrow 10 AM has been cancelled. It will be rescheduled.',
    type: 'error',
    time: '1 day ago',
    read: true,
  },
  {
    id: 'a4',
    title: 'Scholarship Applications Open',
    message: 'Merit-based scholarship applications for 2025-26 are now open. Apply through the student portal by June 1.',
    type: 'success',
    time: '2 days ago',
    read: true,
  },
  {
    id: 'a5',
    title: 'Hostel Maintenance Notice',
    message: 'Hostel Block B water supply will be suspended on May 12 (Sunday) from 8 AM to 4 PM for maintenance.',
    type: 'warning',
    time: '3 days ago',
    read: true,
  },
  {
    id: 'a6',
    title: 'New Course Registration',
    message: 'Open elective registration for next semester starts May 25. Login to the portal to choose your electives.',
    type: 'info',
    time: '4 days ago',
    read: true,
  },
];

export const CATEGORIES = ['All', 'Academic', 'Exam', 'Social', 'Career', 'Cultural', 'Sports'];

export const USER = {
  name: 'Ahmed Raza',
  rollNo: 'CS-2022-045',
  department: 'Computer Science',
  semester: '6th Semester',
  email: 'ahmed.raza@college.edu',
  phone: '+92-300-1234567',
  notifications: true,
  emailAlerts: true,
  smsAlerts: false,
};
